version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: odoo_postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped

  odoo:
    image: odoo:17.0
    container_name: odoo_app
    depends_on:
      - postgres
    env_file: .env
    environment:
      HOST: postgres
      USER: ${USER}
      PASSWORD: ${PASSWORD}
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: odoo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@odoo.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
  odoo_data:
  pgadmin_data: